---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

(TEIDI_recip_record_2017_2022 <- read_delim("TEIDI recipient report 2017-2022.txt", col_names = FALSE)
  %>% rename(histocompatibility_ID = X1)
  %>% rename(center = X2)
  %>% rename(SSN_recipient = X6)
  %>% rename(last_recipient = X7)
  %>% rename(first_recipient = X8)
  %>% rename(middle_recipient = X9)
  %>% rename(organ = X14)
  %>% rename(donor_ID = X15)
  %>% rename(Tx_date = X13)
  %>% mutate(Tx_date = mdy(Tx_date))
  %>% arrange(Tx_date)
  #%>% count(organ) # "KI" should be kidney
  %>% filter(organ == "KI")
  %>% select(histocompatibility_ID, center, SSN_recipient, last_recipient, first_recipient, middle_recipient, donor_ID, organ, Tx_date)
  )

(TEIDI_donor_record_2017_2022 <- read_delim("TEIDI donor report 2017-2022.txt", col_names = FALSE)
  %>% rename(TIEDI_donor_record = X1)
  %>% rename(center = X2)
  %>% rename(last_donor = X6)
  %>% rename(first_donor = X7)
  %>% rename(donor_ID = X8)
  %>% rename(last_recipient = X32)
  %>% rename(first_recipient = X33)
  %>% rename(SSN_recipient = X34)
  %>% rename(organ = X35)
  %>% rename(Tx_date = X36)
  %>% mutate(Tx_date = mdy(Tx_date))
  %>% select(TIEDI_donor_record, donor_ID, last_donor, first_donor, last_recipient, first_recipient, SSN_recipient, Tx_date)
  ) 

```

```{r}
# Join recipient and donor records

(PENN_TEIDI_combined_2017_2022 <- TEIDI_recip_record_2017_2022
 %>% left_join(TEIDI_donor_record_2017_2022, by = "donor_ID", suffix = c(".recipient", ".donor"))
 %>% select(histocompatibility_ID, center, SSN_recipient.recipient, last_recipient.recipient, first_recipient.recipient, middle_recipient, donor_ID, organ, Tx_date.recipient, last_donor, first_donor)
 %>% rename_with(~str_replace(., ".recipient", ""))
 )

# Save as RDS file for linking to LIS data.
saveRDS(PENN_TEIDI_combined_2017_2022, "PENN_TEIDI_combined_2017_2022.rds")
```



